# Generated by Django 5.2 on 2025-04-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_alter_invoice_title_invoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
