# Generated by Django 5.2 on 2025-07-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0004_rename_title_invoice_chantier_remove_invoice_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='rg_percentage',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tva_percentage',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
    ]
