# Generated by Django 5.2 on 2025-07-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0007_quote_quoteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='validity',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='unit',
            field=models.CharField(choices=[('m2', 'M²'), ('ml', 'ML'), ('u', 'Unité'), ('autre', 'Autre')], default='unité', max_length=50),
        ),
    ]
