# Generated by Django 5.2 on 2025-07-18 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0008_quote_validity_alter_quoteitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='factures.quote'),
        ),
    ]
