# Generated by Django 5.2 on 2025-07-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='siret',
            field=models.IntegerField(),
        ),
    ]
