# Generated by Django 5.2 on 2025-07-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_company_siret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='siret',
            field=models.CharField(max_length=50),
        ),
    ]
