# Generated by Django 5.2 on 2025-07-19 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccess',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='useraccess', to=settings.AUTH_USER_MODEL),
        ),
    ]
