# Generated by Django 5.2 on 2025-07-21 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_useraccess_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccess',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='UserAccess',
        ),
    ]
